#!/bin/sh

IMAGE=codercom/code-server:v2
DIR=$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)

cd ${DIR}
docker pull node
docker pull ${IMAGE}
docker build -t novsyama/code-server-ts --build-arg VCS_REF=`git rev-parse --short HEAD` .
docker tag novsyama/code-server-ts novsyama/code-server-ts:local
docker images novsyama/code-server-ts
