#!/bin/bash

TAG=`date +%Y%m%d`
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker tag novsyama/code-server-ts novsyama/code-server-ts:${TAG}
docker push novsyama/code-server-ts:${TAG}
docker push novsyama/code-server-ts

